@startuml
interface IDocument {
    + AuthorId : Guid <<get>> <<set>>
    + Comment : string <<get>> <<set>>
    + DocumentLines : IList<IDocumentLine> <<get>> <<set>>
    + CreatedAt : ZonedDateTime <<get>> <<set>>
    + UpdatedAt : ZonedDateTime <<get>> <<set>>
    + GetTotal() : decimal
}
@enduml
