@startuml
!include ./Domains/RawMaterial.puml
!include ./Domains/PurchaseReceipt.puml
!include ./Domains/ProductComposition.puml
!include ./Domains/AbstractDocument.puml
!include ./Domains/GoodsIssue.puml
!include ./Domains/EndProduct.puml
!include ./Interfaces/IPurchaseReceipt.puml
!include ./Interfaces/IProduct.puml
!include ./Interfaces/IDocumentLine.puml
!include ./Interfaces/IDocument.puml
@enduml
